site_name: Kalba
nav:
  - Home: "index.md"
  - Installation:
      - Requirements: "requirements.md"
      - Linux: "installation_linux.md"
      - Windows: "installation_windows.md"
      - Mac: "installation_mac.md"
      - "Building from source": "installation_building.md"
  - Setup:
      - "Getting Started": "getting_started.md"
      - "Setting up a new language": "new_language.md"
      - "Next Steps": "next_steps.md"
  - Concepts:
      - "Word Knowledge": "word_knowledge.md"
      - Stanza: "stanza.md"
  - Usage:
      - Reader: "reader.md"
  - Configuration:
      - Profiles: "profiles.md"
      - Grammar: "grammar.md"
      - Dictionaries: "dictionaries.md"
      - "Word Knowledge": "word_knowledge_settings.md"
      - Exporting: "exporting.md"
      - Input: "input.md"
      - Stanza: "stanza_settings.md"
  - "Advanced Configuration":
      - "Writing a spyglys parser": "spyglys_parser.md"
      - Backups: "backups.md"
  - "Help":
      - "Common Problems": "common_problems.md"
theme: readthedocs
