name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - run: |
       sudo apt-get update
       sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev glibc-source libc6
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
